### ISSUE TITLE
Fatal Error in Google_REST.php:66

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/hm-top-posts#14]
see: https://github.com/humanmade/hosting-support/issues/209

**Comment by rmccue** [comment]
Copying across the error message for public visibility:
```
[14-May-2018 01:13:34 UTC] PHP Fatal error:  Uncaught Google_ServiceException: Error calling GET https://www.googleapis.com/... (403) Quota Error: profileId ga:XXXXX has too many concurrent connections. in .../hm-top-posts/google-api-php-client/src/io/Google_REST.php:66
Stack trace:
#0 .../hm-top-posts/google-api-php-client/src/io/Google_REST.php(36): Google_REST::decodeHttpResponse(Object(Google_HttpRequest))
#1 .../hm-top-posts/google-api-php-client/src/service/Google_ServiceResource.php(186): Google_REST::execute(Object(Google_HttpRequest))
#2 .../hm-top-posts/google-api-php-client/src/io/Google_REST.php on line 66
```
